# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 894f2ed7327520c9d15e04eae88e7b9fb9ca189bb487f328ae6263cfd7cede2b62268713250bb6a265fad800efb5151f6586f5122d076d065f2da59a67af4737

test:
  secret_key_base: 7b107d76ecc70d6ec111e5cbd889334abbce38d6daf7d0618debc9477207b0d3f4b930412c307aecd619d7e6aecb2219b8aebc006b9b82cd3c384d8604dcdf2c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
